[book]
authors = ["Jan Gaura", "Jakub Beránek", "Daniel Trnka"]
language = "cs"
multilingual = false
src = "src"
title = "Úvod do programování"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/mrlvsb/upr-skripta"
default-theme = "rust"
preferred-dark-theme = "rust"
additional-js = [
  "theme/mode-c_cpp.min.js",
  "src/wasm/xterm.min.js",
  "src/wasm/fit.min.js",
  "src/wasm/shared.js",
  "src/wasm/web.js"
]
additional-css = [
  "theme/css/tufte.css",
  "src/wasm/xterm.min.css"
]
mathjax-support = true
google-analytics = "UA-177556287-1"

[output.html.playground]
editable = true

[output.html.fold]
enable = true
level = 0

[preprocessor.plantuml]
plantuml-cmd="http://www.plantuml.com/plantuml"
